//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3074.
// 
#pragma warning disable 1591

namespace CAFAM.WebPortal.User.SubsidiosWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService_Globant_PortalWeb_BiztalkSubsidiosSoap", Namespace="http://tempuri.org/")]
    public partial class WebService_Globant_PortalWeb_BiztalkSubsidios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAffiliatedUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAffiliatedCompanyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService_Globant_PortalWeb_BiztalkSubsidios() {
            this.Url = global::CAFAM.WebPortal.User.Properties.Settings.Default.CAFAM_WebPortal_User_saplsaflores93_WSSubsidios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAffiliatedUserCompletedEventHandler GetAffiliatedUserCompleted;
        
        /// <remarks/>
        public event GetAffiliatedCompanyCompletedEventHandler GetAffiliatedCompanyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebService_Globant_PortalWeb_BiztalkSubsidios/GetAffiliatedUse" +
            "r", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AffiliatedUser", Namespace="http://BizTalk_Server_Project1.SchemaAfiliatedUser")]
        public AffiliatedUser GetAffiliatedUser([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Globant.PortalWeb.BiztalkSubsidios.SchemaUserRequest")] UserRequest UserRequest) {
            object[] results = this.Invoke("GetAffiliatedUser", new object[] {
                        UserRequest});
            return ((AffiliatedUser)(results[0]));
        }
        
        /// <remarks/>
        public void GetAffiliatedUserAsync(UserRequest UserRequest) {
            this.GetAffiliatedUserAsync(UserRequest, null);
        }
        
        /// <remarks/>
        public void GetAffiliatedUserAsync(UserRequest UserRequest, object userState) {
            if ((this.GetAffiliatedUserOperationCompleted == null)) {
                this.GetAffiliatedUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAffiliatedUserOperationCompleted);
            }
            this.InvokeAsync("GetAffiliatedUser", new object[] {
                        UserRequest}, this.GetAffiliatedUserOperationCompleted, userState);
        }
        
        private void OnGetAffiliatedUserOperationCompleted(object arg) {
            if ((this.GetAffiliatedUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAffiliatedUserCompleted(this, new GetAffiliatedUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebService_Globant_PortalWeb_BiztalkSubsidios/GetAffiliatedCom" +
            "pany", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AffiliatedCompany", Namespace="http://Globant.PortalWeb.BiztalkSubsidios.SchemaAffiliatedCompany")]
        public AffiliatedCompany GetAffiliatedCompany([System.Xml.Serialization.XmlElementAttribute(Namespace="http://Globant.PortalWeb.BiztalkSubsidios.SchemaCompanyRequest")] CompanyRequest CompanyRequest) {
            object[] results = this.Invoke("GetAffiliatedCompany", new object[] {
                        CompanyRequest});
            return ((AffiliatedCompany)(results[0]));
        }
        
        /// <remarks/>
        public void GetAffiliatedCompanyAsync(CompanyRequest CompanyRequest) {
            this.GetAffiliatedCompanyAsync(CompanyRequest, null);
        }
        
        /// <remarks/>
        public void GetAffiliatedCompanyAsync(CompanyRequest CompanyRequest, object userState) {
            if ((this.GetAffiliatedCompanyOperationCompleted == null)) {
                this.GetAffiliatedCompanyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAffiliatedCompanyOperationCompleted);
            }
            this.InvokeAsync("GetAffiliatedCompany", new object[] {
                        CompanyRequest}, this.GetAffiliatedCompanyOperationCompleted, userState);
        }
        
        private void OnGetAffiliatedCompanyOperationCompleted(object arg) {
            if ((this.GetAffiliatedCompanyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAffiliatedCompanyCompleted(this, new GetAffiliatedCompanyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Globant.PortalWeb.BiztalkSubsidios.SchemaUserRequest")]
    public partial class UserRequest {
        
        private int tipoDocumentoField;
        
        private string nroDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk_Server_Project1.SchemaAfiliatedUser")]
    public partial class AffiliatedUser {
        
        private string tipoAfiliadoField;
        
        private AffiliatedUserIdentificacion identificacionField;
        
        private AffiliatedUserIdentificacionPrincipal identificacionPrincipalField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string primerNombreField;
        
        private string segundoNombreField;
        
        private string fechaNacimientoField;
        
        private string sexoField;
        
        private string estadoCivilField;
        
        private string eMailField;
        
        private string nITField;
        
        private string subNITField;
        
        private string nombreORazonSocialField;
        
        private string cargoField;
        
        private string telefonoLaboralField;
        
        private string telefonoMovilField;
        
        private string telefonoField;
        
        private string codigoPaisField;
        
        private string codigoDepartamentoField;
        
        private string ciudadField;
        
        private string localidadField;
        
        private string domicilioTrabajadorField;
        
        private string categoriaSalarialField;
        
        private string claseAfiliadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TipoAfiliado {
            get {
                return this.tipoAfiliadoField;
            }
            set {
                this.tipoAfiliadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AffiliatedUserIdentificacion Identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AffiliatedUserIdentificacionPrincipal IdentificacionPrincipal {
            get {
                return this.identificacionPrincipalField;
            }
            set {
                this.identificacionPrincipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrimerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SegundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrimerNombre {
            get {
                return this.primerNombreField;
            }
            set {
                this.primerNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SegundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EstadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NIT {
            get {
                return this.nITField;
            }
            set {
                this.nITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubNIT {
            get {
                return this.subNITField;
            }
            set {
                this.subNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NombreORazonSocial {
            get {
                return this.nombreORazonSocialField;
            }
            set {
                this.nombreORazonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TelefonoLaboral {
            get {
                return this.telefonoLaboralField;
            }
            set {
                this.telefonoLaboralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TelefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoPais {
            get {
                return this.codigoPaisField;
            }
            set {
                this.codigoPaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoDepartamento {
            get {
                return this.codigoDepartamentoField;
            }
            set {
                this.codigoDepartamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DomicilioTrabajador {
            get {
                return this.domicilioTrabajadorField;
            }
            set {
                this.domicilioTrabajadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CategoriaSalarial {
            get {
                return this.categoriaSalarialField;
            }
            set {
                this.categoriaSalarialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClaseAfiliado {
            get {
                return this.claseAfiliadoField;
            }
            set {
                this.claseAfiliadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk_Server_Project1.SchemaAfiliatedUser")]
    public partial class AffiliatedUserIdentificacion {
        
        private string tipoField;
        
        private string nroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nro {
            get {
                return this.nroField;
            }
            set {
                this.nroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk_Server_Project1.SchemaAfiliatedUser")]
    public partial class AffiliatedUserIdentificacionPrincipal {
        
        private string tipoField;
        
        private string nroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nro {
            get {
                return this.nroField;
            }
            set {
                this.nroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Globant.PortalWeb.BiztalkSubsidios.SchemaCompanyRequest")]
    public partial class CompanyRequest {
        
        private string nITField;
        
        private string subNITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NIT {
            get {
                return this.nITField;
            }
            set {
                this.nITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubNIT {
            get {
                return this.subNITField;
            }
            set {
                this.subNITField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Globant.PortalWeb.BiztalkSubsidios.SchemaAffiliatedCompany")]
    public partial class AffiliatedCompany {
        
        private string nITField;
        
        private string subNITField;
        
        private string razonSocialField;
        
        private string direccionField;
        
        private string nombreJefePersonalField;
        
        private string nombreRepresentanteLegalField;
        
        private string estadoEmpresaField;
        
        private string fechaRetiroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NIT {
            get {
                return this.nITField;
            }
            set {
                this.nITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubNIT {
            get {
                return this.subNITField;
            }
            set {
                this.subNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RazonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NombreJefePersonal {
            get {
                return this.nombreJefePersonalField;
            }
            set {
                this.nombreJefePersonalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NombreRepresentanteLegal {
            get {
                return this.nombreRepresentanteLegalField;
            }
            set {
                this.nombreRepresentanteLegalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EstadoEmpresa {
            get {
                return this.estadoEmpresaField;
            }
            set {
                this.estadoEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaRetiro {
            get {
                return this.fechaRetiroField;
            }
            set {
                this.fechaRetiroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetAffiliatedUserCompletedEventHandler(object sender, GetAffiliatedUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAffiliatedUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAffiliatedUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AffiliatedUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AffiliatedUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetAffiliatedCompanyCompletedEventHandler(object sender, GetAffiliatedCompanyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAffiliatedCompanyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAffiliatedCompanyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AffiliatedCompany Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AffiliatedCompany)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591